version: "3.7"
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: wikigo
      MYSQL_PASSWORD: wikigopwd
      MYSQL_DATABASE: image_wikigo
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      DB_HOST: tcp(db:3306)
    volumes:
      - ./:/docker-entrypoint-initdb.d

  # Api Service
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      API_PORT: "8080"
      MYSQL_USER: wikigo
      MYSQL_PASSWORD: wikigopwd
      MYSQL_DATABASE: image_wikigo
      DB_HOST: tcp(db:3306)
    ports:
      - "8081:8080"
